# -----------------------------------------------------------------------------
# DESCRIPTION
# -----------------------------------------------------------------------------
description.project = ""
description.basin = ""

# -----------------------------------------------------------------------------
# DATA
# -----------------------------------------------------------------------------
# simulation forcings
data.simulation.rainfall = ""
data.simulation.pet = ""
data.simulation.air-temp = ""
data.simulation.snowfall = ""
# forecast forcings
data.forecast.rainfall = ""
data.forecast.pet = ""
data.forecast.air-temp = ""
data.forecast.snowfall = ""
# observations
data.observation.streamflow = ""
data.observation.piezo-level = ""
# influences
data.influence.pumping_or_injection = ""
# others
data.other.weather_tile_weights = ""
