channels:
  - conda-forge
dependencies:
  - python>=3.9
  - numpy
  - pandas
  - toml  # mygardenia
  - evalhyd-python  # mygardenia
  - matplotlib  # mygardenia
  - requests  # myhubeau
  - cdsapi  # mycds
  - xarray  # mycds
  - cfgrib  # mycds
  - dask  # mycds
  - netcdf4  # mycds
