[time]
# Pas de temps :  0=Journalier 1=Pentadaire 2=Décadaire 3=Mensuel 4=Autre 5=5_Jours 7=7_Jours
rainfall_snowfall_pumping_timestep = "0"
pet_timestep = "0"
air-temp_timestep = "0"
streamflow_piezo-level_timestep = "0"
# Format : 0=Gardénia_Sequentiel  1=Gardénia_Annuaire  2=Libre  3=Excel
rainfall_snowfall_pumping_format = "3"
pet_format = "3"
air-temp_format = "3"
streamflow_piezo-level_format = "3"

# Unité de durée des Pas si non-standard (sec,min,heu,jou,moi,ann)
non_standard_timestep_duration_unit = "Standard"
# Durée du pas de temps si non-standard (dans l'unité) ***
non_standard_timestep_duration = 1

[general_settings]
# Profil d'utilisation : 0=simple ; A=Avancé (Neige, Pompage, Prévi etc.)
user_profile = "0"
# Mode d'exécution (C = Contrôle sur écran ; Déf=Rapide ; D=Direct ; M=Muet)
execution_mode = "M"

# Nombre de Sites (Bassins) à modéliser successivement
n_sites = 1
# Type de donnée pour Prévision (0=Débits de Rivière , 1=Niveaux de Nappe)
forecast_data_type = "0"
# Opération : Déf=Calcul ; A=Actualisation seule du fichier des paramètres
computation_mode = ""

# Observations de Débits de Rivière : Importance (entier : 0 à 10 ;  0=Non)
streamflow_obs_weight = 5
# Observations de Niveaux de Nappe  : Importance (entier : 0 à 10 ;  0=Non)
piezo-level_obs_weight = 2
# Calcul des Débits de Rivière : (0=Non  ;  1=Oui)
calc_streamflow = true
# Calcul des Niveaux de Nappe  : (0=Non  ;  1=Oui)
calc_piezo-level = true

# Sauvegarde de la Recharge et de la Pluie Efficace (0=Non  ;  1=Oui)
save_recharge_effective-rainfall = true
# Sauvegarde des Débit/Niveaux simulés : (0=Non  ;  1=Oui)
save_streamflow_piezo-level = true
# Sauvegarde des termes du Bilan : (0=Non ; 1=Annuel ; 2=Mensuel ; 3=Tous les pas de temps)
save_water-balance = "0"
# Sauvegarde de la 'Réponse impulsionnelle' et de la 'Réponse Cumulée' (1=Oui)
save_impulse_and_cumulative_response = false

# Allègement du Listing (0=Complet ; 1=Allégé ; 2=Supprimé)
verbose = "0"
# Schéma de calcul (0=Gardénia ; 5=Ruissell,Drainage ; etc.)
computation_scheme = "0"
# Dessin de la série simulée (0=non ; 1=Oui ; 2=Oui avec décomposition)
draw_series = "2"
# Pondération pour calibration (0=Non ; 2= ++Étiages ; 99= Racine_Débit; 97= Logar_Débits)
transform_calibration_data = "0"
# Minimisation du biais de simulation des Débits Rivière (0 = Non ; 100 = 100 %)
minimise_streamflow_bias = false
# Pompage influençant les Débits de Rivière (0=Non ; 1=Oui ; 2=Oui en rivière)
pumping_influencing_streamflow = "0"
# Pompage influençant les Niveaux de Nappe (0=Non ; 1=Oui)
pumping_influencing_piezo-level = "0"

# Calcul avec Prévision (0=Non ; 1=Oui ; -1=Préparation uniquement) [3, 4 = Particulier]
forecast_run = false
# Méthode de Prévision (0=Ajustement Réservoirs ; 1=Décalage simple ; 2=Décalage avec 1/2 vie)
forecast_method = "0"

# Schéma d'échanges souterr. avec extérieur (0=% Débit Souterr. (++) ; 1=Facteur Niv_Souterr.)
underground_exchange_scheme = "0"

# Bilan journalier même si pluie Décadaire ou Mensuelle (0=Non ; 1=Oui)
daily_summary = false

# Prise en compte de la Neige (0=Non  ;  1=Oui)
consider_snow = false
# Précipitations neigeuses dans un fichier propre (0 = avec pluies ; 1 = fichier séparé)
snowfall_in_file = "0"

# Données par années hydrologiques [début 1 août] (0=années Civiles ; 1=années Hydrologiques)
data_per_hydro_year = false

# Perte de Débit : 0=Non ; 1=Perd le Debit Souterrain le plus Lent ; -1=Perd le Ruissellement
streamflow_loss = "0"

# Analyse de Sensibilité (0=Non  ;  1=Oui uniquement analyse de Sensibilité)
sensitivity_analysis = false

# Données de tous les sites dans différentes colonnes d'un même fichier (Déf=0)
site_data_in_columns = "0"
# Numéro de la 'colonne' des Pluies       : Déf=0 <=> 1ère colonne de données
simulation_rainfall_column_number = 0
# Numéro de la 'colonne' des ETP          : Déf=0=Identique à la pluie
simulation_pet_column_number = 0
# Numéro de la 'colonne' des Débits       : Déf=0=Identique à la pluie
simulation_streamflow_column_number = 0
# Numéro de la 'colonne' des Niveaux      : Déf=0=Identique à la pluie
simulation_piezo-level_column_number = 0
# Numéro de la 'colonne' des Températures : Déf=0=Identique à la pluie
simulation_air-temp_column_number = 0
# Numéro de la 'colonne' de la Neige      : Déf=0=Identique à la pluie
simulation_snowfall_column_number = 0
# Numéro de la 'colonne' des Pompages     : Déf=0=Identique à la pluie
simulation_pumping_column_number = 0
# Numéro de la 'colonne' des Pluies pour Prévision  : Déf=0=Identique à la pluie
forecast_rainfall_column_number = 0
# Numéro de la 'colonne' des ETP pour Prévision     : Déf=0=Identique à la pluie
forecast_pet_column_number = 0
# Numéro de la 'colonne' des Tempér. pour Prévision : Déf=0=Identique à la pluie
forecast_air-temp_column_number = 0
# Numéro de la 'colonne' de la Neige pour Prévision : Déf=0=Identique à la pluie
forecast_snowfall_column_number = 0

# Météo (Pluie, ETP, ...) pondérée à chaque pas [1=Fich. annuels SAFRAN , 2=Fichier unique]
weather_data_weighting_per_time_step = "0"
# Sauvegarde de la météo pondérée => Fichier (futus runs + rapides et portables) [1=Oui]
save_weather_data_weighting = false

# Couplage avec le coupleur OpenPalm (0=Non ; 1=Couplage Météo)
openpalm_coupling = "0"

[filter_settings]
# Valeur Minimale/Maximale du Débit de Rivière Observé prise en compte (0 = toutes)
observed_streamflow_to_consider = {min=0.0, max=0.0}

# Valeur Minimale/Maximale du Niveau de Nappe Observé prise en compte (0 = toutes)
observed_piezo-level_to_consider = {min=0.0, max=0.0}

# Débit Rivière réservé (valeur minimale possible pour les débits simulés) (Déf=0)
simulated_streamflow_lower_limit_to_apply = 0.0

[forecast_settings]
# Coefficient de réajustement pour la prévision [0 à 1]
readjustment_factor = 0.0

# Écart-type de l'alimentation du Réservoir intermédiaire  (pour la prévision)
standard_deviation_of_intermediate_reservoir = 0.0
# Écart-type de l'alimentation du Réservoir Souterrain n°1 (pour la prévision)
standard_deviation_of_groundwater_reservoir_1 = 0.0
# Écart-type de l'alimentation du Réservoir Souterrain n°2 (pour la prévision)
standard_deviation_of_groundwater_reservoir_2 = 0.0

# Écart-type des observations de niveau de nappe (pour la prévision)
standard_deviation_of_observed_piezo-level = 0.0
# Temps de 1/2 vie de l'écart de prévision de Débit de rivière  (pas de temps)
half-life_fall_streamflow_forecast = 0.0
# Temps de 1/2 vie de l'écart de prévision de Niveau de Nappe   (pas de temps)
half-life_fall_piezo-level_forecast = 0.0

[basin_settings]
# Position des Données du bassin > N° de la 'colonne' des données : (-1 => N° d'ordre du bassin) Déf=0 <=> Col. n°1
data.basin_column_number_in_data = 0

# Nombre d'années des séries de données (Pluie, ETP, Observations) [0 => Toutes]
time.simulation.n_years_in_data = 0
# Date de la première année des données (par ex. 2017)
time.simulation.first_year = 1985
# Numéro du Mois initial [Déf=1] (si durée non-standard) ; ex. 12 pour décembre
time.simulation.first_month = 0
# Numéro du Jour initial [Déf=1] (si durée non-standard) ; ex. 31 pour 31 (décembre)
time.simulation.first_day = 0
# Heure initiale [Déf=0] (si durée non-standard) ; par ex. 15 pour 15h30
time.simulation.first_hour = 0
# Minute initiale [Déf=0] (si durée non-standard) ; Par ex. 30 pour 15h30
time.simulation.first_minute = 0

# --- /!\ OBSOLETE ---
# Durée des pluies en moyenne par pas de temps (%) (utilisation avancée) [défaut = 100 %]
time.rainfall_mean_duration_within_timestep = 0
# --------------------

# Nombre d'années de données du fichier de pluies etc. pour la prévision
time.forecast.n_years_in_data = 0
# Date de la première année des fichiers météo de prévision [si journalier ou horaire] (déf = 0)
time.forecast.first_year = 0
# Numéro du mois [si journalier, horaire ou mensuel] (ou n° du pas de temps) d'émiss. de la prévision
time.forecast.issue_month = 0
# Jour d'émission de la prévision (1-31) si pas de temps journalier (sinon : 0)
time.forecast.issue_day = 0

# Portée de la prévision (en nombre de pas de temps de prévision)
time.forecast.span = 0

# Numéro de l'année utilisée pour les pompages pendant la prévision (ex. 2019) Déf 0 => Avant-dernière
time.forecast.pumping_year = 0

# Décalage dans la série des Pluies [+5 => Retarde de 5 pas ; -4 Avance de 4 pas]
time.delay_in_rainfall_data = 0
# Décalage de la série des Débits/Niveaux observés [ex: -2 => Avance de 2 pas]
time.delay_in_streamflow_piezo-level_data = 0

# État initial : 0=Pluie Efficace moyenne ; -1=Réservoirs vides ; -2=RuMax vide aussi
model.initialisation.antecedent_conditions = 0

# Nombre d'années démarrage (-n pour générer n année moyennes fictives de démarrage)
model.initialisation.spinup.n_years = 4
# Nombre de cycles de démarrage (déf. = 1)
model.initialisation.spinup.n_cycles = 1

# Nombre d'années finales à ignorer pour la calibration (déf = 0) [< 0 => n° de la dernière année]
model.calibration.n_tail_years_to_trim = 0
# Nombre maximum d'itérations pour la calibration (0 => Aucune itération, pas de calibration)
model.calibration.max_iterations = 250

# Nombre de réservoirs souterrains (1 ou 2 ou -1=Réservoir double avec seuil)   [déf = 1]
model.structure.n_groundwater_reservoirs = 1
# Numéro du réservoir souterrain <=> Niveau nappe (si 2 réservoirs souterrains) [déf = 1]
model.structure.groundwater_reservoir_for_piezo-level = 1

# Perte du débit de Ruissellement par Débordement au-dessus du Seuil [0=Non ; 1=Perte ; 2 => Rés Sout]
model.structure.intermediate_runoff_by_overspill = 0
# Décroissance de l'évapotranspiration si saturation du réservoir sol < 50% (0=Non ; 1=Oui)
model.structure.intermediate_reservoir_evapotranspiration_decrease_only_when_half_empty = false
# Schéma à taux de ruissellement constant (pour comparaison uniquement ; déconseillé) (0=Non ; 1=Oui)
model.structure.constant_runoff_ratio_scheme = false
# Méthode de calcul du coefficient d'Emmagasinement [0 = Corrélation ; 1 = Optimisation entre bornes]
model.structure.storage_coefficient_computation_scheme = "0"

[physical_parameters]
# Pluie Eff. annuelle pour initialis. (0=équil.) (mm/an)
annual_effective-rainfall = {val=0.0}
# Débit extérieur éventuel                        (m3/s)
external_flow = {val=0.0, opt=false}
# Superficie du bassin versant                     (km2)
basin_area = {val=524.0, opt=false}

# Correction globale des Pluies                      (%)
rainfall_correction = {val=0.0, opt=false, min=-10.0, max=10.0}
# Correction globale de l'ETP                        (%)
pet_correction = {val=0.0, opt=false, min=-15.0, max=15.0}
# Facteur de correction de la superficie du bassin   (-)
basin_area_correction = {val=1.0, opt=false, min=0.02, max=50.0}

# Capacité du réservoir sol 'réserve utile'         (mm)   [RUMAX]
thornthewaite_reservoir_capacity = {val=0.0, opt=false, min=0.0, max=500.0}
# Capacité du réservoir sol progressif              (mm)   [Sx]
progressive_reservoir_capacity = {val=150.0, opt=true, min=0.0, max=650.0}
# Hauteur de répartition Ruissellement-Percolation  (mm)   [RUIPER]
intermediate_runoff_seepage = {val=50.0, opt=true, min=1.0, max=9999.0}
# Temps de 1/2 percolation vers la nappe          (mois)   [THG]
intermediate_half-life_seepage = {val=0.5, opt=true, min=0.05, max=10.0}
# Temps de 1/2 tarissement du débit souterr. n°1  (mois)   [TG1]
groundwater_1_drainage = {val=0.0, opt=true, min=0.05, max=15.0}
# Temps de 1/2 transfert vers la nappe profonde   (mois)   [TG12]
groundwater_1_2_exchange = {val=0.0, opt=false, min=0.05, max=50.0}
# Seuil d'écoulement souterrain n°1 (rés. double)   (mm)   [SEUIL]
groundwater_1_double_outflow_threshold = {val=0.0, opt=false, min=0.0, max=9999.0}
# Temps de 1/2 tarissement du débit souterr. n°2  (mois)   [TG2]
groundwater_2_drainage = {val=0.0, opt=false, min=0.05, max=50.0}
# Facteur d'échange souterrain externe               (%)   [FACT_ECHANG]
groundwater_external_exchange = {val=0.0, opt=false, min=-70.0, max=80.0}

# Temps de réaction ('retard') du débit   (pas de temps)
time_of_concentration = {val=0.0, opt=false, min=0.0, max=10.0}

# Déficit initial du réservoir sol 'réserve utile'  (mm)
thornthewaite_reservoir_initial_deficit = {val=0.0, opt=false, min=0.0, max=999.0}
# Déficit initial du réservoir sol progressif       (mm)
progressive_reservoir_initial_deficit = {val=0.0, opt=false, min=0.0, max=999.0}

# Seuil de ruissellement par débordement            (mm)
intermediate_runoff_threshold = {val=0.0, opt=false, min=0.0, max=9999.0}
# Temps de 1/2 ruissell. par débordement  (Pas de temps)
intermediate_half-life_runoff_by_overspill = {val=0.0, opt=false, min=0.05, max=9999.0}
# Temps de 1/2 décroiss. maximal du ruissellement (mois)
intermediate_half-life_max_runoff_decrease = {val=0.0, opt=false, min=0.0001, max=1000.0}

# Niveau de base local de la nappe               (m NGF)   [NB]
groundwater_base_level = {val=0.0, opt=false}
# Coefficient d'emmagasinement de la nappe           (%)   [SG]
groundwater_storage_coefficient = {val=0.0, opt=false, min=0.5, max=35.0}

# Correction globale de la température              (°C)
air-temp_correction = {val=0.0, opt=false, min=-3.0, max=3.0}
# Taux de rétention de la neige                      (%)
snowfall_retention_factor = {val=0.0, opt=false, min=0.001, max=30.0}
# Facteur d'évaporation de la neige                  (%)
snow_evaporation_factor = {val=0.0, opt=false, min=0.0, max=20.0}
# Correction de fonte de la neige par la pluie       (%)
snow_melt_correction_with_rainfall = {val=0.0, opt=false, min=0.0, max=20.0}
# Température seuil de fonte naturelle de la neige  (°C)
natural_snow_melting_threshold = {val=0.0, opt=false, min=-2.0, max=2.0}
# Constante de fonte par la température     (mm/°C/jour)
snow_melt_degree_day_factor = {val=0.0, opt=false, min=0.001, max=7.0}
# Fonte de la neige au contact du sol     (1/10 mm/jour)
snow_melting_in_contact_with_soil = {val=0.0, opt=false, min=0.001, max=20.0}

# Coefficient d'influence du pompage => Débit Rivière (-)
pumping_river_influence_factor = {val=1.0, opt=false}
# Temps de 1/2 montée du pompage infl. => Rivière  (mois)
pumping_river_half-life_rise = {val=0.0, opt=false, min=0.05, max=10.0}
# Temps de 1/2 stabilisation du pompage => Rivière (mois)
pumping_river_half-life_fall = {val=0.0, opt=false, min=0.05, max=15.0}
# Coefficient d'influence du pompage => Niveau Nappe  (-)
pumping_groundwater_influence_factor = {val=1.0, opt=false}
# Temps de 1/2 montée du pompage infl. => Nappe    (mois)
pumping_groundwater_half-life_rise = {val=0.0, opt=false, min=0.05, max=10.0}
# Temps de 1/2 stabilisation du pompage => Nappe   (mois)
pumping_groundwater_half-life_fall = {val=0.0, opt=false, min=0.05, max=15.0}
